# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c83f541f36bbb62483fe5e48db3cb2286c061ebac167be71fb5ef3462970dc0901bb7ed19b1d85a0998db3986fa8265e2e860a8be2035c13d330478e8229dfd2

test:
  secret_key_base: 6453a590f80eef5f2d202b2c14dbd893812beb4937a8ed5da8b4d2c0f70b9d2bf145a6ecb42367f9f1848508892f0ce8fd08859ccea489e69415b0422fb02b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
